# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = false
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				chest_minecart = true
				tropical_fish = true
				pufferfish = true
				glow_squid = true
				bat = true
				skeleton = true
				zombie = true
				enderman = true
				spider = true
				item = true
				bee = true
				zombie_villager = true
				witch = true
				sheep = true
				cow = true
				creeper = true
				wolf = true
				pig = true
				chicken = true
				rabbit = true
				frog = true
				allay = true
				area_effect_cloud = true
				armor_stand = true
				arrow = true
				axolotl = true
				blaze = true
				boat = true
				chest_boat = true
				cat = true
				cave_spider = true
				cod = true
				dolphin = true
				donkey = true
				dragon_fireball = true
				drowned = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				firework_rocket = true
				fox = true
				ghast = true
				giant = true
				goat = true
				guardian = true
				hoglin = true
				horse = true
				husk = true
				illusioner = true
				iron_golem = true
				item_frame = true
				fireball = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				tnt_minecart = true

			[light_sources.settings.entities.naturalist]
				bass = true
				lizard = true
				rhino = true
				boar = true
				cardinal = true
				deer = true
				alligator = true
				tortoise = true
				catfish = true
				bear = true
				butterfly = true

			[light_sources.settings.entities.varietyaquatic]
				yellowfin = true
				piranha = true
				tetra = true
				betta = true

			[light_sources.settings.entities.creeperoverhaul]
				cave_creeper = true
				ocean_creeper = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

			[light_sources.settings.entities.mythicmobs]
				mushroom_thing = true
				chupacabra = true
				drake = true
				kobold = true
				kobold_warrior = true

