zombiesBurnInSunlight = false
doScream = false
frostZombieChance = 0.01
fireZombieChance = 0.01

[spawn]
spawnInstantly = false
minPlayerDistance = 16.0
maxZombieCount = 64
allowedDimensions = ["overworld"]

[spawn.instantSpawning]
maxSpawnAttemptsPerTick = 100
maxSpawnsPerTick = 10

[spawn.axisSpawnParameters]
chance = 0.1
min = 16
max = 48

[spawn.planeSpawnParameters]
chance = 0.1
min = 16
max = 48

[spawn.boxSpawnParameters]
chance = 0.1
min = 24
max = 64

[spawn.timeRange]
min = 13000
max = 20000

[Armor]
helmets = ["iron", "gold", "chainmail", "leather", "turtle"]
chestplates = ["iron", "gold", "chainmail", "leather"]
leggings = ["iron", "gold", "chainmail", "leather"]
boots = ["iron", "gold", "chainmail", "leather"]

[Armor.chancesPerSlot]
chances = [0.1, 0.1, 0.1, 0.1]
defaultChance = 0.1

[Armor.materialWeights]
weights = [1, 10, 100, 50, 50, 100]
weightsForExtraEntries = 10

[Weapon]
swords = ["iron", "gold", "stone", "wood"]
shovels = ["iron", "gold", "stone", "wood"]
pickaxes = ["iron", "gold", "stone", "wood"]
axes = ["iron", "gold", "stone", "wood"]
hoes = ["iron", "gold", "stone", "wood"]
chance = 0.1

[Weapon.weightsForTools]
weights = [100, 20, 20, 75, 1]
weightsForExtraEntries = 100

[Weapon.commonWeights]
weights = [1, 10, 100, 50, 50, 100]
weightsForExtraEntries = 100

[enchantmentLevelRange]
min = 5
max = 40

[statusEffects]
effects = ["speed", "haste", "strength", "regeneration", "resistance", "fire_resistance", "water_breathing", "health_boost", "absorption", "saturation", "conduit_power", "dolphins_grace"]
maxTimeInTicks = -1
incrementalChances = [0.1, 0.5, 0.8, 0.9]
maxAmplifier = 5
